---
title: "About this site"

---

This is a website (and github repository) of data and code for our work about impact of COVID on TB notifications in Blantyre Malawi.

We are the Malawi Liverpool Wellcome Population Health group; a group of reseachers affiliated with Malawi-Liverpool-Wellcome, Liverpool School of Tropical Medicine, London School of Hygiene and Tropical Medicine, College of Medicine at University of Malawi and University of Sheffield.

The TB electronic reporting system is a partnership between our group and Malawi National TB programme and Blantyre District Health Office.

Some more information about our research group is available at Dr Peter MacPherson's group manual here https://petermacp.github.io/mlw.public.health.group/ . 

More data about TB epidemiology in Blantyre is here https://github.com/petermacp/BlantyreTBEpi (a companion package to the paper 'MacPherson, P. et al. Disparities in access to diagnosis and care in Blantyre, Malawi, identified through enhanced tuberculosis surveillance and spatial analysis. BMC Medicine 17, 21 (2019). https://doi.org/10.1186/s12916-019-1260-6'
 )

If you have any questions, we'd be very happy to discuss.  A good first port of call is probably peter.macpherson [at] lstmed [dot] ac [dot] uk or rachael.burke [at] lshtm [dot] ac [dot] uk.